const tree = require('../lib/tree')
const data = [
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "基础科学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A",
        "SYS_FLD_SYSID": "1",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "基础科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "708"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "工程科技Ⅰ辑",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B",
        "SYS_FLD_SYSID": "2",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "14",
        "SYS_FLD_CLASS_ALIAS": "工程科技Ⅰ辑",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "905"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "工程科技Ⅱ辑",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C",
        "SYS_FLD_SYSID": "3",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "15",
        "SYS_FLD_CLASS_ALIAS": "工程科技Ⅱ辑",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1034"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农业科技",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D",
        "SYS_FLD_SYSID": "4",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "农业科技",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "559"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "医药卫生科技",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E",
        "SYS_FLD_SYSID": "5",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "28",
        "SYS_FLD_CLASS_ALIAS": "医药卫生科技",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1026"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "哲学与人文科学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F",
        "SYS_FLD_SYSID": "6",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "24",
        "SYS_FLD_CLASS_ALIAS": "哲学与人文科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "333"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "社会科学Ⅰ辑",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G",
        "SYS_FLD_SYSID": "7",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "17",
        "SYS_FLD_CLASS_ALIAS": "社会科学Ⅰ辑",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "465"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "社会科学Ⅱ辑",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H",
        "SYS_FLD_SYSID": "8",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "社会科学Ⅱ辑",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "979"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "信息科技",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I",
        "SYS_FLD_SYSID": "9",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "信息科技",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "459"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "经济与管理科学",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J",
        "SYS_FLD_SYSID": "10",
        "SYS_FLD_CLASS_GRADE": "1",
        "SYS_FLD_CHILD_COUNT": "24",
        "SYS_FLD_CLASS_ALIAS": "经济与管理科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "0010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "902"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "自然科学理论与方法",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A001",
        "SYS_FLD_SYSID": "11",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "自然科学理论与方法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "6"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "数学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A002",
        "SYS_FLD_SYSID": "18",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "数学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "52"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "非线性科学与系统科学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A003",
        "SYS_FLD_SYSID": "102",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "非线性科学与系统科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "10"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "力学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A004",
        "SYS_FLD_SYSID": "110",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "力学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "16"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "物理学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A005",
        "SYS_FLD_SYSID": "162",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "19",
        "SYS_FLD_CLASS_ALIAS": "物理学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "37"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "生物学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A006",
        "SYS_FLD_SYSID": "245",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "16",
        "SYS_FLD_CLASS_ALIAS": "生物学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "86"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "天文学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A007",
        "SYS_FLD_SYSID": "304",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "天文学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "自然地理学和测绘学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A008",
        "SYS_FLD_SYSID": "315",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "自然地理学和测绘学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "44"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "气象学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A009",
        "SYS_FLD_SYSID": "334",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "气象学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "32"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "海洋学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A010",
        "SYS_FLD_SYSID": "347",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "14",
        "SYS_FLD_CLASS_ALIAS": "海洋学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "25"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "地质学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A011",
        "SYS_FLD_SYSID": "362",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "19",
        "SYS_FLD_CLASS_ALIAS": "地质学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "151"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "地球物理学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A012",
        "SYS_FLD_SYSID": "423",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "15",
        "SYS_FLD_CLASS_ALIAS": "地球物理学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "39"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "资源科学",
        "SYS_FLD_PARENT_CODE": "A",
        "SYS_FLD_CLASS_CODE": "A013",
        "SYS_FLD_SYSID": "449",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "资源科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00010013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "16"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "化学",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B014",
        "SYS_FLD_SYSID": "465",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "化学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "54"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "无机化工",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B015",
        "SYS_FLD_SYSID": "537",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "无机化工",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "73"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "有机化工",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B016",
        "SYS_FLD_SYSID": "562",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "有机化工",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "156"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "燃料化工",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B017",
        "SYS_FLD_SYSID": "636",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "燃料化工",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "21"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "一般化学工业",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B018",
        "SYS_FLD_SYSID": "658",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "一般化学工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "石油天然气工业",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B019",
        "SYS_FLD_SYSID": "684",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "石油天然气工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "70"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "材料科学",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B020",
        "SYS_FLD_SYSID": "710",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "材料科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "矿业工程",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B021",
        "SYS_FLD_SYSID": "733",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "矿业工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "75"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "金属学及金属工艺",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B022",
        "SYS_FLD_SYSID": "778",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "金属学及金属工艺",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "92"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "冶金工业",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B023",
        "SYS_FLD_SYSID": "851",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "11",
        "SYS_FLD_CLASS_ALIAS": "冶金工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "65"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "轻工业手工业",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B024",
        "SYS_FLD_SYSID": "914",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "14",
        "SYS_FLD_CLASS_ALIAS": "轻工业手工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "154"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "一般服务业",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B025",
        "SYS_FLD_SYSID": "953",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "一般服务业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "安全科学与灾害防治",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B026",
        "SYS_FLD_SYSID": "961",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "安全科学与灾害防治",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "32"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "环境科学与资源利用",
        "SYS_FLD_PARENT_CODE": "B",
        "SYS_FLD_CLASS_CODE": "B027",
        "SYS_FLD_SYSID": "999",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "环境科学与资源利用",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00020014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "84"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "工业通用技术及设备",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C028",
        "SYS_FLD_SYSID": "1033",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "工业通用技术及设备",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "54"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "机械工业",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C029",
        "SYS_FLD_SYSID": "1072",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "机械工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "57"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "仪器仪表工业",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C030",
        "SYS_FLD_SYSID": "1127",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "18",
        "SYS_FLD_CLASS_ALIAS": "仪器仪表工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "34"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "航空航天科学与工程",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C031",
        "SYS_FLD_SYSID": "1146",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "航空航天科学与工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "51"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "武器工业与军事技术",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C032",
        "SYS_FLD_SYSID": "1191",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "武器工业与军事技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "41"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "铁路运输",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C033",
        "SYS_FLD_SYSID": "1207",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "铁路运输",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "35"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "公路与水路运输",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C034",
        "SYS_FLD_SYSID": "1216",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "公路与水路运输",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "79"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "汽车工业",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C035",
        "SYS_FLD_SYSID": "1234",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "14",
        "SYS_FLD_CLASS_ALIAS": "汽车工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "32"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "船舶工业",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C036",
        "SYS_FLD_SYSID": "1258",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "16",
        "SYS_FLD_CLASS_ALIAS": "船舶工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "26"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "水利水电工程",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C037",
        "SYS_FLD_SYSID": "1284",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "水利水电工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "75"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "建筑科学与工程",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C038",
        "SYS_FLD_SYSID": "1311",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "建筑科学与工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "159"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "动力工程",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C039",
        "SYS_FLD_SYSID": "1379",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "动力工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "41"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "核科学技术",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C040",
        "SYS_FLD_SYSID": "1420",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "核科学技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "19"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "新能源",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C041",
        "SYS_FLD_SYSID": "1430",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "新能源",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "3"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "电力工业",
        "SYS_FLD_PARENT_CODE": "C",
        "SYS_FLD_CLASS_CODE": "C042",
        "SYS_FLD_SYSID": "1439",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "电力工业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00030015",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "123"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农业基础科学",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D043",
        "SYS_FLD_SYSID": "1509",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "农业基础科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "25"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农业工程",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D044",
        "SYS_FLD_SYSID": "1543",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "农业工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "33"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农艺学",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D045",
        "SYS_FLD_SYSID": "1577",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "农艺学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "5"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "植物保护",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D046",
        "SYS_FLD_SYSID": "1603",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "植物保护",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "22"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农作物",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D047",
        "SYS_FLD_SYSID": "1633",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "农作物",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "36"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "园艺",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D048",
        "SYS_FLD_SYSID": "1691",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "园艺",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "38"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "林业",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D049",
        "SYS_FLD_SYSID": "1737",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "林业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "89"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "畜牧与动物医学",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D050",
        "SYS_FLD_SYSID": "1802",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "畜牧与动物医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "92"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "蚕蜂与野生动物保护",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D051",
        "SYS_FLD_SYSID": "1850",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "蚕蜂与野生动物保护",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "15"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "水产和渔业",
        "SYS_FLD_PARENT_CODE": "D",
        "SYS_FLD_CLASS_CODE": "D052",
        "SYS_FLD_SYSID": "1875",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "水产和渔业",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00040010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "29"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "医药卫生方针政策与法律法规研究",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E053",
        "SYS_FLD_SYSID": "1902",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "医药卫生方针政策与法律法规研究",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "33"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "医学教育与医学边缘学科",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E054",
        "SYS_FLD_SYSID": "1913",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "医学教育与医学边缘学科",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "14"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "预防医学与卫生学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E055",
        "SYS_FLD_SYSID": "1920",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "预防医学与卫生学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "67"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中医学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E056",
        "SYS_FLD_SYSID": "1949",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "16",
        "SYS_FLD_CLASS_ALIAS": "中医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "88"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中药学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E057",
        "SYS_FLD_SYSID": "1998",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "11",
        "SYS_FLD_CLASS_ALIAS": "中药学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "23"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中西医结合",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E058",
        "SYS_FLD_SYSID": "2010",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "中西医结合",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "17"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "基础医学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E059",
        "SYS_FLD_SYSID": "2031",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "基础医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "52"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "临床医学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E060",
        "SYS_FLD_SYSID": "2066",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "临床医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "77"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "感染性疾病及传染病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E061",
        "SYS_FLD_SYSID": "2119",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "11",
        "SYS_FLD_CLASS_ALIAS": "感染性疾病及传染病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "14"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "心血管系统疾病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E062",
        "SYS_FLD_SYSID": "2156",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "心血管系统疾病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "31"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "呼吸系统疾病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E063",
        "SYS_FLD_SYSID": "2178",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "呼吸系统疾病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "消化系统疾病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E064",
        "SYS_FLD_SYSID": "2196",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "消化系统疾病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "16"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "内分泌腺及全身性疾病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E065",
        "SYS_FLD_SYSID": "2218",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "内分泌腺及全身性疾病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "10"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "外科学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E066",
        "SYS_FLD_SYSID": "2242",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "外科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "67"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "泌尿科学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E067",
        "SYS_FLD_SYSID": "2298",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "泌尿科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050015",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "10"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "妇产科学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E068",
        "SYS_FLD_SYSID": "2315",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "妇产科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050016",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "17"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "儿科学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E069",
        "SYS_FLD_SYSID": "2344",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "儿科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050017",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "16"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "神经病学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E070",
        "SYS_FLD_SYSID": "2370",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "神经病学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050018",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "21"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "精神病学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E071",
        "SYS_FLD_SYSID": "2388",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "精神病学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050019",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "9"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "肿瘤学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E072",
        "SYS_FLD_SYSID": "2396",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "肿瘤学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050020",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "29"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "眼科与耳鼻咽喉科",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E073",
        "SYS_FLD_SYSID": "2449",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "眼科与耳鼻咽喉科",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050021",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "25"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "口腔科学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E074",
        "SYS_FLD_SYSID": "2481",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "口腔科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050022",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "19"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "皮肤病与性病",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E075",
        "SYS_FLD_SYSID": "2496",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "皮肤病与性病",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050023",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "特种医学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E076",
        "SYS_FLD_SYSID": "2516",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "特种医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050024",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "28"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "急救医学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E077",
        "SYS_FLD_SYSID": "2544",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "急救医学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050025",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "6"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "军事医学与卫生",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E078",
        "SYS_FLD_SYSID": "2578",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "军事医学与卫生",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050026",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "7"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "药学",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E079",
        "SYS_FLD_SYSID": "2583",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "药学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050027",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "60"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "生物医学工程",
        "SYS_FLD_PARENT_CODE": "E",
        "SYS_FLD_CLASS_CODE": "E080",
        "SYS_FLD_SYSID": "2604",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "生物医学工程",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00050028",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "14"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "文艺理论",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F081",
        "SYS_FLD_SYSID": "2617",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "文艺理论",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "世界文学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F082",
        "SYS_FLD_SYSID": "2626",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "世界文学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国文学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F083",
        "SYS_FLD_SYSID": "2631",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "中国文学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "32"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国语言文字",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F084",
        "SYS_FLD_SYSID": "2656",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "中国语言文字",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "18"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "外国语言文字",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F085",
        "SYS_FLD_SYSID": "2678",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "外国语言文字",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "音乐舞蹈",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F086",
        "SYS_FLD_SYSID": "2693",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "音乐舞蹈",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "22"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "戏剧电影与电视艺术",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F087",
        "SYS_FLD_SYSID": "2703",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "戏剧电影与电视艺术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "23"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "美术书法雕塑与摄影",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F088",
        "SYS_FLD_SYSID": "2714",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "美术书法雕塑与摄影",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "30"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "地理",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F089",
        "SYS_FLD_SYSID": "2720",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "地理",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "文化",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F090",
        "SYS_FLD_SYSID": "2725",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "文化",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "9"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "史学理论",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F091",
        "SYS_FLD_SYSID": "2730",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "史学理论",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "3"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "世界历史",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F092",
        "SYS_FLD_SYSID": "2739",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "世界历史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "2"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国通史",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F093",
        "SYS_FLD_SYSID": "2753",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "中国通史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "11"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国民族与地方史志",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F094",
        "SYS_FLD_SYSID": "2762",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "中国民族与地方史志",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "21"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国古代史",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F095",
        "SYS_FLD_SYSID": "2765",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "中国古代史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060015",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国近现代史",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F096",
        "SYS_FLD_SYSID": "2788",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "中国近现代史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060016",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "6"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "考古",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F097",
        "SYS_FLD_SYSID": "2806",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "考古",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060017",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "26"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "人物传记",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F098",
        "SYS_FLD_SYSID": "2810",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "人物传记",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060018",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "0"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "哲学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F099",
        "SYS_FLD_SYSID": "2826",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "哲学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060019",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "11"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "逻辑学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F100",
        "SYS_FLD_SYSID": "2841",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "逻辑学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060020",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "0"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "伦理学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F101",
        "SYS_FLD_SYSID": "2843",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "伦理学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060021",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "2"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "心理学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F102",
        "SYS_FLD_SYSID": "2848",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "心理学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060022",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "美学",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F103",
        "SYS_FLD_SYSID": "2850",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "美学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060023",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "宗教",
        "SYS_FLD_PARENT_CODE": "F",
        "SYS_FLD_CLASS_CODE": "F104",
        "SYS_FLD_SYSID": "2852",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "宗教",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00060024",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "马克思主义",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G105",
        "SYS_FLD_SYSID": "2858",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "马克思主义",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "5"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国共产党",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G106",
        "SYS_FLD_SYSID": "2878",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "中国共产党",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "39"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "政治学",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G107",
        "SYS_FLD_SYSID": "2898",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "政治学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中国政治与国际政治",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G108",
        "SYS_FLD_SYSID": "2908",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "中国政治与国际政治",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "89"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "思想政治教育",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G109",
        "SYS_FLD_SYSID": "2942",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "思想政治教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "行政学及国家行政管理",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G110",
        "SYS_FLD_SYSID": "2949",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "行政学及国家行政管理",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "35"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "政党及群众组织",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G111",
        "SYS_FLD_SYSID": "2957",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "政党及群众组织",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "7"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "军事",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G112",
        "SYS_FLD_SYSID": "2979",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "军事",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "公安",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G113",
        "SYS_FLD_SYSID": "2986",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "13",
        "SYS_FLD_CLASS_ALIAS": "公安",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "49"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "法理、法史",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G114",
        "SYS_FLD_SYSID": "3000",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "法理、法史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "宪法",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G115",
        "SYS_FLD_SYSID": "3005",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "宪法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "0"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "行政法及地方法制",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G116",
        "SYS_FLD_SYSID": "3007",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "行政法及地方法制",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "民商法",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G117",
        "SYS_FLD_SYSID": "3014",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "民商法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "刑法",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G118",
        "SYS_FLD_SYSID": "3018",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "刑法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "2"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "经济法",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G119",
        "SYS_FLD_SYSID": "3020",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "经济法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070015",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "4"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "诉讼法与司法制度",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G120",
        "SYS_FLD_SYSID": "3024",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "诉讼法与司法制度",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070016",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "18"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "国际法",
        "SYS_FLD_PARENT_CODE": "G",
        "SYS_FLD_CLASS_CODE": "G121",
        "SYS_FLD_SYSID": "3032",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "国际法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00070017",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "0"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "社会科学理论与方法",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H122",
        "SYS_FLD_SYSID": "3036",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "社会科学理论与方法",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "3"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "社会学及统计学",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H123",
        "SYS_FLD_SYSID": "3042",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "社会学及统计学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "34"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "民族学",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H124",
        "SYS_FLD_SYSID": "3052",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "民族学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "人口学与计划生育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H125",
        "SYS_FLD_SYSID": "3054",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "1",
        "SYS_FLD_CLASS_ALIAS": "人口学与计划生育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "人才学与劳动科学",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H126",
        "SYS_FLD_SYSID": "3056",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "人才学与劳动科学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "教育理论与教育管理",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H127",
        "SYS_FLD_SYSID": "3059",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "教育理论与教育管理",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "36"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "学前教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H128",
        "SYS_FLD_SYSID": "3092",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "学前教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "初等教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H129",
        "SYS_FLD_SYSID": "3098",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "初等教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "中等教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H130",
        "SYS_FLD_SYSID": "3119",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "中等教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "高等教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H131",
        "SYS_FLD_SYSID": "3139",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "11",
        "SYS_FLD_CLASS_ALIAS": "高等教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "42"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "职业教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H132",
        "SYS_FLD_SYSID": "3151",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "职业教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "2"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "成人教育与特殊教育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H133",
        "SYS_FLD_SYSID": "3159",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "7",
        "SYS_FLD_CLASS_ALIAS": "成人教育与特殊教育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "13"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "体育",
        "SYS_FLD_PARENT_CODE": "H",
        "SYS_FLD_CLASS_CODE": "H134",
        "SYS_FLD_SYSID": "3176",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "9",
        "SYS_FLD_CLASS_ALIAS": "体育",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00080013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "42"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "无线电电子学",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I135",
        "SYS_FLD_SYSID": "3212",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "无线电电子学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "81"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "电信技术",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I136",
        "SYS_FLD_SYSID": "3272",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "16",
        "SYS_FLD_CLASS_ALIAS": "电信技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "79"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "计算机硬件技术",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I137",
        "SYS_FLD_SYSID": "3297",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "计算机硬件技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "10"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "计算机软件及计算机应用",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I138",
        "SYS_FLD_SYSID": "3325",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "12",
        "SYS_FLD_CLASS_ALIAS": "计算机软件及计算机应用",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "53"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "互联网技术",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I139",
        "SYS_FLD_SYSID": "3362",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "互联网技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "8"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "自动化技术",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I140",
        "SYS_FLD_SYSID": "3381",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "自动化技术",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "45"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "新闻与传媒",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I141",
        "SYS_FLD_SYSID": "3426",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "新闻与传媒",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "44"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "出版",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I142",
        "SYS_FLD_SYSID": "3436",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "出版",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "22"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "图书情报与数字图书馆",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I143",
        "SYS_FLD_SYSID": "3445",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "图书情报与数字图书馆",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "37"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "档案及博物馆",
        "SYS_FLD_PARENT_CODE": "I",
        "SYS_FLD_CLASS_CODE": "I144",
        "SYS_FLD_SYSID": "3460",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "档案及博物馆",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00090010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "26"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "宏观经济管理与可持续发展",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J145",
        "SYS_FLD_SYSID": "3470",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "宏观经济管理与可持续发展",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100001",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "95"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "经济理论及经济思想史",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J146",
        "SYS_FLD_SYSID": "3479",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "经济理论及经济思想史",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100002",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "经济体制改革",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J147",
        "SYS_FLD_SYSID": "3484",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "经济体制改革",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100003",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "51"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "经济统计",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J148",
        "SYS_FLD_SYSID": "3495",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "经济统计",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100004",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "0"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "农业经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J149",
        "SYS_FLD_SYSID": "3501",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "农业经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100005",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "94"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "工业经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J150",
        "SYS_FLD_SYSID": "3538",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "工业经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100006",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "85"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "交通运输经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J151",
        "SYS_FLD_SYSID": "3581",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "交通运输经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100007",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "19"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "企业经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J152",
        "SYS_FLD_SYSID": "3588",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "企业经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100008",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "52"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "旅游",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J153",
        "SYS_FLD_SYSID": "3600",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "8",
        "SYS_FLD_CLASS_ALIAS": "旅游",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100009",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "5"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "文化经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J154",
        "SYS_FLD_SYSID": "3616",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "10",
        "SYS_FLD_CLASS_ALIAS": "文化经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100010",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "信息经济与邮政经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J155",
        "SYS_FLD_SYSID": "3627",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "信息经济与邮政经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100011",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "21"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "服务业经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J156",
        "SYS_FLD_SYSID": "3633",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "服务业经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100012",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "1"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "贸易经济",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J157",
        "SYS_FLD_SYSID": "3639",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "贸易经济",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100013",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "73"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "财政与税收",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J158",
        "SYS_FLD_SYSID": "3655",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "3",
        "SYS_FLD_CLASS_ALIAS": "财政与税收",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100014",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "29"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "金融",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J159",
        "SYS_FLD_SYSID": "3665",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "金融",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100015",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "60"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "证券",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J160",
        "SYS_FLD_SYSID": "3681",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "证券",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100016",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "3"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "保险",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J161",
        "SYS_FLD_SYSID": "3686",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "保险",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100017",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "6"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "投资",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J162",
        "SYS_FLD_SYSID": "3691",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "5",
        "SYS_FLD_CLASS_ALIAS": "投资",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100018",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "6"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "会计",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J163",
        "SYS_FLD_SYSID": "3708",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "会计",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100019",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "33"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "审计",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J164",
        "SYS_FLD_SYSID": "3721",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "审计",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100020",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "15"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "市场研究与信息",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J165",
        "SYS_FLD_SYSID": "3728",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "市场研究与信息",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100021",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "5"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "管理学",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J166",
        "SYS_FLD_SYSID": "3733",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "6",
        "SYS_FLD_CLASS_ALIAS": "管理学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100022",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "15"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "领导学与决策学",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J167",
        "SYS_FLD_SYSID": "3740",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "2",
        "SYS_FLD_CLASS_ALIAS": "领导学与决策学",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100023",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "10"
    },
    {
        "SYS_FLD_CHILD_SORTSN": "0",
        "SYS_FLD_RECORD_COUNT": "0",
        "SYS_FLD_CLASS_NAME": "科学研究管理",
        "SYS_FLD_PARENT_CODE": "J",
        "SYS_FLD_CLASS_CODE": "J168",
        "SYS_FLD_SYSID": "3743",
        "SYS_FLD_CLASS_GRADE": "2",
        "SYS_FLD_CHILD_COUNT": "4",
        "SYS_FLD_CLASS_ALIAS": "科学研究管理",
        "SYS_FLD_PREVSILIBING_CODE": "",
        "SYS_FLD_SYS_CODE": "00100024",
        "SYS_FLD_CHILD_FLAG": "1",
        "SYS_FLD_NEXTSILIBING_CODE": "",
        "SYS_FLD_CJFD_COUNT": "12"
    }
]
const rs = tree.listToTree(data,{
    id:'SYS_FLD_CLASS_CODE',
    pid:'SYS_FLD_PARENT_CODE',
    children:'children'
})
